services:
    PoP\Comments\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Comments\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true

    PoP\Comments\FieldInterfaceResolvers\:
        resource: '../src/FieldInterfaceResolvers/*'
        public: true
