parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Comments\Hooks\:
        resource: '../src/Hooks/*'
        public: true
